---
- name: Install Dependecies and Libs for rails app
  apt:
    name: '{{ item }}'
    state: present
  with_items: 
    - '{{app_dependencies}}'
- name:       'Install ruby dependencies'
  apt:
    pkg:      '{{ item }}'
    state:    'installed'
  with_items: 'ruby_dependencies'