---
- name: Install Dependecies and Libs for rails app
  apt:
    name: '{{ item }}'
    state: present
  with_items: 
    - 'nodejs'
    - 'libmagick++-dev'
    - 'imagemagick'
    - 'libpq-dev'

- name: Install bundler
  shell: /usr/local/rbenv/shims/gem install bundler