---
- name: Add Nginx repo
  apt_repository:
    repo:  'ppa:nginx/stable'
    update_cache: 'true'

- name: Install Nginx
  apt:
    name: 'nginx'
    state: latest

- name: Configuration Nginx
  template: src=etc/nginx/nginx.j2 dest=/etc/nginx/nginx.conf
  notify: restarting nginx

- name: Host Configuration
  template: src=etc/nginx/sites-enabled/hostconf.j2 dest=/etc/nginx/sites-enabled/{{ app_name }}.conf
  notify: reloading nginx